### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by B10prajapati**
- Integration of typescript.
- Seperation of Connection Events to a seperate folder i.e connection/connection.ts, for easier mainatainence.
- Creation of test file and test cases for connection.ts file
- import/exports adopted from pervious require/module.exports format

### CODE REVIEW

**Comment by B10prajapati** [comment]
Use of  Enum: SocketEvent:
```
export enum SocketEvent {
  created = "created",
  joined = "joined",
  join = "join",
  full = "full",
  ready = "ready",
  candidate = "candidate",
  offer = "offer",
  answer = "answer",
}
```
Use Case:
` socket.emit(SocketEvent.joined)`
Benefit: Prevents wrong spelling input.

**Review by rohitjoey — COMMENTED** [review]
OK cool. Project structure made I guess?

**Review by nirjalpraj — APPROVED** [review]

**Review by nirjalpraj — COMMENTED** [review]
Great work!

**Review by Nirajan9860 — COMMENTED** [review]
nice work

**Pull request merged**
